# Generated by Django 4.1.5 on 2023-02-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='useer',
            new_name='user',
        ),
    ]
