# Generated by Django 4.1.5 on 2023-02-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('current', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Workshops', verbose_name='Imagen')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
