# Generated by Django 4.1.5 on 2023-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
