# Generated by Django 4.1.5 on 2023-02-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshops_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='image',
            field=models.ImageField(upload_to='Workshops_images'),
        ),
    ]
