# Generated by Django 4.1.5 on 2023-02-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshops_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
