# Generated by Django 4.1.5 on 2023-02-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshops_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshops',
            name='image',
        ),
        migrations.AddField(
            model_name='workshops',
            name='workshop_image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops_images'),
        ),
    ]
