# Generated by Django 4.1.5 on 2023-01-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Supplies',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
