# Generated by Django 4.1.5 on 2023-01-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_rename_products_supplies_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='image',
            field=models.ImageField(default='', upload_to='Supplies', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
