# Generated by Django 4.1.5 on 2023-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supplies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='image',
        ),
        migrations.AddField(
            model_name='supplies',
            name='supplie_image',
            field=models.ImageField(blank=True, null=True, upload_to='Supplies_images'),
        ),
    ]
